# Generated by Django 6.0.3 on 2026-04-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_formsubmissionapproval_approver_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='formschema',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
