# Generated by Django 6.0.3 on 2026-04-09 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formschema_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='pending_action_by',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='pending_action_by',
            field=models.ManyToManyField(blank=True, related_name='pending_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
