# Generated by Django 6.0.3 on 2026-04-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_formsubmission_pending_action_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formschema',
            name='slug',
        ),
        migrations.AddField(
            model_name='formtype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
